"""initial database structure

Revision ID: 0f222f55058a
Revises: 
Create Date: 2026-07-21 15:03:29.977273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f222f55058a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('impUpdates',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('monthlyUpdates',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('betaTesting',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('betaTesting',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('monthlyUpdates',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('impUpdates',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
